version: '3.9'

services:
  app:
    build:
      context: .
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    ports:
      - 8000:8000
    volumes:
      - ./app:/app
      - ./data/web:/vol/web
    environment:
      - SECRET_KEY=devsecretkey
      - DEBUG=1
      - DB_HOST=db
      - DB_NAME=devdb
      - DB_USER=devuser
      - DB_PASS=changeme
      - CELERY_BROKER=redis://redis:6379/0
    container_name: django_app
    depends_on:
      - db

  db:
    image: postgres:13-alpine
    environment:
      - POSTGRES_DB=devdb
      - POSTGRES_USER=devuser
      - POSTGRES_PASSWORD=changeme
    container_name: postgres_db
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    container_name: redis
  
  celery:
    restart: always
    build:
      context: .
    command: celery -A app worker -l info
    volumes:
      - ./app:/app
    environment:
      - SECRET_KEY=devsecretkey
      - DB_HOST=db
      - DB_NAME=devdb
      - DB_USER=devuser
      - DB_PASS=changeme
      - CELERY_BROKER=redis://redis:6379/0
    container_name: celery
    depends_on:
      - db
      - redis
      - app
  
  celery-beat:
    restart: always
    build:
      context: .
    command: celery -A app beat -l info
    volumes:
      - ./app:/app
    environment:
      - SECRET_KEY=devsecretkey
      - CELERY_BROKER=redis://redis:6379/0
    container_name: beat
    depends_on:
      - db
      - redis
      - app

volumes:
  postgres-data: